spring.application.name=news-digest

spring.datasource.url=jdbc:postgresql://localhost:5432/news_digest
spring.datasource.username=news_digest
spring.datasource.password=news_digest

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true